// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: callback_order_events.proto

package callbackevents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_PLACEHOLDER_ORDER_TYPE OrderType = 0
	OrderType_WITHDRAW               OrderType = 1
	OrderType_DEPOSIT                OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "PLACEHOLDER_ORDER_TYPE",
		1: "WITHDRAW",
		2: "DEPOSIT",
	}
	OrderType_value = map[string]int32{
		"PLACEHOLDER_ORDER_TYPE": 0,
		"WITHDRAW":               1,
		"DEPOSIT":                2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_order_events_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_callback_order_events_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{0}
}

type OrderStatus int32

const (
	OrderStatus_PLACEHOLDER_ORDER_STATUS OrderStatus = 0
	OrderStatus_ACCEPTED                 OrderStatus = 1
	OrderStatus_CREATED                  OrderStatus = 2
	OrderStatus_PROCESSING               OrderStatus = 3
	OrderStatus_CONFIRMED                OrderStatus = 4
	OrderStatus_FAILED                   OrderStatus = 5
	OrderStatus_SUCCESS                  OrderStatus = 6
	OrderStatus_CANCELED                 OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PLACEHOLDER_ORDER_STATUS",
		1: "ACCEPTED",
		2: "CREATED",
		3: "PROCESSING",
		4: "CONFIRMED",
		5: "FAILED",
		6: "SUCCESS",
		7: "CANCELED",
	}
	OrderStatus_value = map[string]int32{
		"PLACEHOLDER_ORDER_STATUS": 0,
		"ACCEPTED":                 1,
		"CREATED":                  2,
		"PROCESSING":               3,
		"CONFIRMED":                4,
		"FAILED":                   5,
		"SUCCESS":                  6,
		"CANCELED":                 7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_order_events_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_callback_order_events_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{1}
}

type OperationType int32

const (
	OperationType_OPERATION_TYPE_PLACEHOLDER OperationType = 0
	OperationType_OPERATION_TYPE_SPENT       OperationType = 1
	OperationType_OPERATION_TYPE_RECEIVE     OperationType = 2
	OperationType_OPERATION_TYPE_FEE         OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_PLACEHOLDER",
		1: "OPERATION_TYPE_SPENT",
		2: "OPERATION_TYPE_RECEIVE",
		3: "OPERATION_TYPE_FEE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_PLACEHOLDER": 0,
		"OPERATION_TYPE_SPENT":       1,
		"OPERATION_TYPE_RECEIVE":     2,
		"OPERATION_TYPE_FEE":         3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_order_events_proto_enumTypes[2].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_callback_order_events_proto_enumTypes[2]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{2}
}

type BcTxStatus int32

const (
	BcTxStatus_PLACEHOLDER_BC_TX_STATUS        BcTxStatus = 0
	BcTxStatus_BC_TX_IN_MINING                 BcTxStatus = 1
	BcTxStatus_BC_TX_SUCCESS                   BcTxStatus = 2
	BcTxStatus_BC_TX_EXECUTION_FAILED          BcTxStatus = 3
	BcTxStatus_BC_TX_WAITING_FOR_CONFIRMATIONS BcTxStatus = 4
)

// Enum value maps for BcTxStatus.
var (
	BcTxStatus_name = map[int32]string{
		0: "PLACEHOLDER_BC_TX_STATUS",
		1: "BC_TX_IN_MINING",
		2: "BC_TX_SUCCESS",
		3: "BC_TX_EXECUTION_FAILED",
		4: "BC_TX_WAITING_FOR_CONFIRMATIONS",
	}
	BcTxStatus_value = map[string]int32{
		"PLACEHOLDER_BC_TX_STATUS":        0,
		"BC_TX_IN_MINING":                 1,
		"BC_TX_SUCCESS":                   2,
		"BC_TX_EXECUTION_FAILED":          3,
		"BC_TX_WAITING_FOR_CONFIRMATIONS": 4,
	}
)

func (x BcTxStatus) Enum() *BcTxStatus {
	p := new(BcTxStatus)
	*p = x
	return p
}

func (x BcTxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BcTxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_order_events_proto_enumTypes[3].Descriptor()
}

func (BcTxStatus) Type() protoreflect.EnumType {
	return &file_callback_order_events_proto_enumTypes[3]
}

func (x BcTxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BcTxStatus.Descriptor instead.
func (BcTxStatus) EnumDescriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{3}
}

type EstimationFeeIdentify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimationFeeIdentify) Reset() {
	*x = EstimationFeeIdentify{}
	mi := &file_callback_order_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimationFeeIdentify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimationFeeIdentify) ProtoMessage() {}

func (x *EstimationFeeIdentify) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimationFeeIdentify.ProtoReflect.Descriptor instead.
func (*EstimationFeeIdentify) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{0}
}

func (x *EstimationFeeIdentify) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type EstimationFeeUnitIdentify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimationFeeUnitIdentify) Reset() {
	*x = EstimationFeeUnitIdentify{}
	mi := &file_callback_order_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimationFeeUnitIdentify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimationFeeUnitIdentify) ProtoMessage() {}

func (x *EstimationFeeUnitIdentify) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimationFeeUnitIdentify.ProtoReflect.Descriptor instead.
func (*EstimationFeeUnitIdentify) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{1}
}

func (x *EstimationFeeUnitIdentify) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type OrderIdentity struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UUID              string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	ExternalOrderUUID string                 `protobuf:"bytes,2,opt,name=ExternalOrderUUID,proto3" json:"ExternalOrderUUID,omitempty"`
	ProviderOrderUUID string                 `protobuf:"bytes,3,opt,name=ProviderOrderUUID,proto3" json:"ProviderOrderUUID,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderIdentity) Reset() {
	*x = OrderIdentity{}
	mi := &file_callback_order_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIdentity) ProtoMessage() {}

func (x *OrderIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIdentity.ProtoReflect.Descriptor instead.
func (*OrderIdentity) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderIdentity) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *OrderIdentity) GetExternalOrderUUID() string {
	if x != nil {
		return x.ExternalOrderUUID
	}
	return ""
}

func (x *OrderIdentity) GetProviderOrderUUID() string {
	if x != nil {
		return x.ProviderOrderUUID
	}
	return ""
}

type BcTxIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxID          string                 `protobuf:"bytes,1,opt,name=TxID,proto3" json:"TxID,omitempty"`
	Meta          []byte                 `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BcTxIdentity) Reset() {
	*x = BcTxIdentity{}
	mi := &file_callback_order_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BcTxIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BcTxIdentity) ProtoMessage() {}

func (x *BcTxIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BcTxIdentity.ProtoReflect.Descriptor instead.
func (*BcTxIdentity) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{3}
}

func (x *BcTxIdentity) GetTxID() string {
	if x != nil {
		return x.TxID
	}
	return ""
}

func (x *BcTxIdentity) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CurrencyIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyIdentity) Reset() {
	*x = CurrencyIdentity{}
	mi := &file_callback_order_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyIdentity) ProtoMessage() {}

func (x *CurrencyIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyIdentity.ProtoReflect.Descriptor instead.
func (*CurrencyIdentity) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{4}
}

func (x *CurrencyIdentity) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type CurrencyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    *CurrencyIdentity      `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=Decimals,proto3" json:"Decimals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyInfo) Reset() {
	*x = CurrencyInfo{}
	mi := &file_callback_order_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyInfo) ProtoMessage() {}

func (x *CurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyInfo.ProtoReflect.Descriptor instead.
func (*CurrencyInfo) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{5}
}

func (x *CurrencyInfo) GetIdentifier() *CurrencyIdentity {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *CurrencyInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CurrencyInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

type BcTxOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	CurrencyInfo  *CurrencyInfo          `protobuf:"bytes,5,opt,name=CurrencyInfo,proto3" json:"CurrencyInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BcTxOperation) Reset() {
	*x = BcTxOperation{}
	mi := &file_callback_order_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BcTxOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BcTxOperation) ProtoMessage() {}

func (x *BcTxOperation) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BcTxOperation.ProtoReflect.Descriptor instead.
func (*BcTxOperation) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{6}
}

func (x *BcTxOperation) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BcTxOperation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BcTxOperation) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BcTxOperation) GetCurrencyInfo() *CurrencyInfo {
	if x != nil {
		return x.CurrencyInfo
	}
	return nil
}

type OperationsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*BcTxOperation       `protobuf:"bytes,1,rep,name=Operations,proto3" json:"Operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationsList) Reset() {
	*x = OperationsList{}
	mi := &file_callback_order_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationsList) ProtoMessage() {}

func (x *OperationsList) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationsList.ProtoReflect.Descriptor instead.
func (*OperationsList) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{7}
}

func (x *OperationsList) GetOperations() []*BcTxOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type OwnerWalletInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletUUID    string                 `protobuf:"bytes,1,opt,name=WalletUUID,proto3" json:"WalletUUID,omitempty"`
	AccountUUID   string                 `protobuf:"bytes,2,opt,name=AccountUUID,proto3" json:"AccountUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerWalletInfo) Reset() {
	*x = OwnerWalletInfo{}
	mi := &file_callback_order_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerWalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerWalletInfo) ProtoMessage() {}

func (x *OwnerWalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerWalletInfo.ProtoReflect.Descriptor instead.
func (*OwnerWalletInfo) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{8}
}

func (x *OwnerWalletInfo) GetWalletUUID() string {
	if x != nil {
		return x.WalletUUID
	}
	return ""
}

func (x *OwnerWalletInfo) GetAccountUUID() string {
	if x != nil {
		return x.AccountUUID
	}
	return ""
}

type BcTxInfo struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	NetworkIdentifier uint32                     `protobuf:"varint,1,opt,name=NetworkIdentifier,proto3" json:"NetworkIdentifier,omitempty"`
	BcTxIdentifier    *BcTxIdentity              `protobuf:"bytes,2,opt,name=BcTxIdentifier,proto3" json:"BcTxIdentifier,omitempty"`
	Confirmations     uint64                     `protobuf:"varint,3,opt,name=Confirmations,proto3" json:"Confirmations,omitempty"`
	BlockNumber       uint64                     `protobuf:"varint,4,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	Operations        map[string]*OperationsList `protobuf:"bytes,5,rep,name=Operations,proto3" json:"Operations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status            BcTxStatus                 `protobuf:"varint,6,opt,name=Status,proto3,enum=callbackevents.BcTxStatus" json:"Status,omitempty"`
	RealFee           uint64                     `protobuf:"varint,7,opt,name=RealFee,proto3" json:"RealFee,omitempty"`
	ExplorerURL       string                     `protobuf:"bytes,8,opt,name=ExplorerURL,proto3" json:"ExplorerURL,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BcTxInfo) Reset() {
	*x = BcTxInfo{}
	mi := &file_callback_order_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BcTxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BcTxInfo) ProtoMessage() {}

func (x *BcTxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BcTxInfo.ProtoReflect.Descriptor instead.
func (*BcTxInfo) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{9}
}

func (x *BcTxInfo) GetNetworkIdentifier() uint32 {
	if x != nil {
		return x.NetworkIdentifier
	}
	return 0
}

func (x *BcTxInfo) GetBcTxIdentifier() *BcTxIdentity {
	if x != nil {
		return x.BcTxIdentifier
	}
	return nil
}

func (x *BcTxInfo) GetConfirmations() uint64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *BcTxInfo) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BcTxInfo) GetOperations() map[string]*OperationsList {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *BcTxInfo) GetStatus() BcTxStatus {
	if x != nil {
		return x.Status
	}
	return BcTxStatus_PLACEHOLDER_BC_TX_STATUS
}

func (x *BcTxInfo) GetRealFee() uint64 {
	if x != nil {
		return x.RealFee
	}
	return 0
}

func (x *BcTxInfo) GetExplorerURL() string {
	if x != nil {
		return x.ExplorerURL
	}
	return ""
}

type Order struct {
	state                       protoimpl.MessageState     `protogen:"open.v1"`
	OrderIdentifier             *OrderIdentity             `protobuf:"bytes,1,opt,name=OrderIdentifier,proto3" json:"OrderIdentifier,omitempty"`
	Type                        OrderType                  `protobuf:"varint,2,opt,name=Type,proto3,enum=callbackevents.OrderType" json:"Type,omitempty"`
	Status                      OrderStatus                `protobuf:"varint,3,opt,name=Status,proto3,enum=callbackevents.OrderStatus" json:"Status,omitempty"`
	NetworkIdentifier           uint32                     `protobuf:"varint,4,opt,name=NetworkIdentifier,proto3" json:"NetworkIdentifier,omitempty"`
	ProviderIdentifier          uint32                     `protobuf:"varint,5,opt,name=ProviderIdentifier,proto3" json:"ProviderIdentifier,omitempty"`
	MerchantIdentifier          string                     `protobuf:"bytes,6,opt,name=MerchantIdentifier,proto3" json:"MerchantIdentifier,omitempty"`
	AddressIdentifier           string                     `protobuf:"bytes,7,opt,name=AddressIdentifier,proto3" json:"AddressIdentifier,omitempty"`
	Amount                      uint64                     `protobuf:"varint,8,opt,name=Amount,proto3" json:"Amount,omitempty"`
	RealFee                     uint64                     `protobuf:"varint,9,opt,name=RealFee,proto3" json:"RealFee,omitempty"`
	EstimationFeeUnitIdentifier *EstimationFeeUnitIdentify `protobuf:"bytes,10,opt,name=EstimationFeeUnitIdentifier,proto3" json:"EstimationFeeUnitIdentifier,omitempty"`
	OwnerWallet                 *OwnerWalletInfo           `protobuf:"bytes,11,opt,name=OwnerWallet,proto3" json:"OwnerWallet,omitempty"`
	CurrencyIdentifier          *CurrencyIdentity          `protobuf:"bytes,12,opt,name=CurrencyIdentifier,proto3" json:"CurrencyIdentifier,omitempty"`
	BcTx                        []*BcTxInfo                `protobuf:"bytes,13,rep,name=BcTx,proto3" json:"BcTx,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_callback_order_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetOrderIdentifier() *OrderIdentity {
	if x != nil {
		return x.OrderIdentifier
	}
	return nil
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_PLACEHOLDER_ORDER_TYPE
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PLACEHOLDER_ORDER_STATUS
}

func (x *Order) GetNetworkIdentifier() uint32 {
	if x != nil {
		return x.NetworkIdentifier
	}
	return 0
}

func (x *Order) GetProviderIdentifier() uint32 {
	if x != nil {
		return x.ProviderIdentifier
	}
	return 0
}

func (x *Order) GetMerchantIdentifier() string {
	if x != nil {
		return x.MerchantIdentifier
	}
	return ""
}

func (x *Order) GetAddressIdentifier() string {
	if x != nil {
		return x.AddressIdentifier
	}
	return ""
}

func (x *Order) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetRealFee() uint64 {
	if x != nil {
		return x.RealFee
	}
	return 0
}

func (x *Order) GetEstimationFeeUnitIdentifier() *EstimationFeeUnitIdentify {
	if x != nil {
		return x.EstimationFeeUnitIdentifier
	}
	return nil
}

func (x *Order) GetOwnerWallet() *OwnerWalletInfo {
	if x != nil {
		return x.OwnerWallet
	}
	return nil
}

func (x *Order) GetCurrencyIdentifier() *CurrencyIdentity {
	if x != nil {
		return x.CurrencyIdentifier
	}
	return nil
}

func (x *Order) GetBcTx() []*BcTxInfo {
	if x != nil {
		return x.BcTx
	}
	return nil
}

type OrderEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventIdentity      string                 `protobuf:"bytes,1,opt,name=EventIdentity,proto3" json:"EventIdentity,omitempty"`
	NetworkIdentifier  uint32                 `protobuf:"varint,2,opt,name=NetworkIdentifier,proto3" json:"NetworkIdentifier,omitempty"`
	ProviderIdentifier uint32                 `protobuf:"varint,3,opt,name=ProviderIdentifier,proto3" json:"ProviderIdentifier,omitempty"`
	MerchantIdentifier string                 `protobuf:"bytes,4,opt,name=MerchantIdentifier,proto3" json:"MerchantIdentifier,omitempty"`
	OrderIdentifier    string                 `protobuf:"bytes,5,opt,name=OrderIdentifier,proto3" json:"OrderIdentifier,omitempty"`
	Type               string                 `protobuf:"bytes,6,opt,name=Type,proto3" json:"Type,omitempty"`
	Producer           string                 `protobuf:"bytes,7,opt,name=Producer,proto3" json:"Producer,omitempty"`
	Message            string                 `protobuf:"bytes,8,opt,name=Message,proto3" json:"Message,omitempty"`
	OrderInfo          *Order                 `protobuf:"bytes,9,opt,name=OrderInfo,proto3" json:"OrderInfo,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_callback_order_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_callback_order_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_callback_order_events_proto_rawDescGZIP(), []int{11}
}

func (x *OrderEvent) GetEventIdentity() string {
	if x != nil {
		return x.EventIdentity
	}
	return ""
}

func (x *OrderEvent) GetNetworkIdentifier() uint32 {
	if x != nil {
		return x.NetworkIdentifier
	}
	return 0
}

func (x *OrderEvent) GetProviderIdentifier() uint32 {
	if x != nil {
		return x.ProviderIdentifier
	}
	return 0
}

func (x *OrderEvent) GetMerchantIdentifier() string {
	if x != nil {
		return x.MerchantIdentifier
	}
	return ""
}

func (x *OrderEvent) GetOrderIdentifier() string {
	if x != nil {
		return x.OrderIdentifier
	}
	return ""
}

func (x *OrderEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderEvent) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *OrderEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OrderEvent) GetOrderInfo() *Order {
	if x != nil {
		return x.OrderInfo
	}
	return nil
}

var File_callback_order_events_proto protoreflect.FileDescriptor

const file_callback_order_events_proto_rawDesc = "" +
	"\n" +
	"\x1bcallback_order_events.proto\x12\x0ecallbackevents\"+\n" +
	"\x15EstimationFeeIdentify\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\"/\n" +
	"\x19EstimationFeeUnitIdentify\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\"\x7f\n" +
	"\rOrderIdentity\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12,\n" +
	"\x11ExternalOrderUUID\x18\x02 \x01(\tR\x11ExternalOrderUUID\x12,\n" +
	"\x11ProviderOrderUUID\x18\x03 \x01(\tR\x11ProviderOrderUUID\"6\n" +
	"\fBcTxIdentity\x12\x12\n" +
	"\x04TxID\x18\x01 \x01(\tR\x04TxID\x12\x12\n" +
	"\x04Meta\x18\x02 \x01(\fR\x04Meta\"&\n" +
	"\x10CurrencyIdentity\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\"\x84\x01\n" +
	"\fCurrencyInfo\x12@\n" +
	"\n" +
	"Identifier\x18\x01 \x01(\v2 .callbackevents.CurrencyIdentityR\n" +
	"Identifier\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x1a\n" +
	"\bDecimals\x18\x03 \x01(\rR\bDecimals\"\x99\x01\n" +
	"\rBcTxOperation\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05Index\x12\x18\n" +
	"\aAddress\x18\x02 \x01(\tR\aAddress\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x04R\x06Amount\x12@\n" +
	"\fCurrencyInfo\x18\x05 \x01(\v2\x1c.callbackevents.CurrencyInfoR\fCurrencyInfo\"O\n" +
	"\x0eOperationsList\x12=\n" +
	"\n" +
	"Operations\x18\x01 \x03(\v2\x1d.callbackevents.BcTxOperationR\n" +
	"Operations\"S\n" +
	"\x0fOwnerWalletInfo\x12\x1e\n" +
	"\n" +
	"WalletUUID\x18\x01 \x01(\tR\n" +
	"WalletUUID\x12 \n" +
	"\vAccountUUID\x18\x02 \x01(\tR\vAccountUUID\"\xdf\x03\n" +
	"\bBcTxInfo\x12,\n" +
	"\x11NetworkIdentifier\x18\x01 \x01(\rR\x11NetworkIdentifier\x12D\n" +
	"\x0eBcTxIdentifier\x18\x02 \x01(\v2\x1c.callbackevents.BcTxIdentityR\x0eBcTxIdentifier\x12$\n" +
	"\rConfirmations\x18\x03 \x01(\x04R\rConfirmations\x12 \n" +
	"\vBlockNumber\x18\x04 \x01(\x04R\vBlockNumber\x12H\n" +
	"\n" +
	"Operations\x18\x05 \x03(\v2(.callbackevents.BcTxInfo.OperationsEntryR\n" +
	"Operations\x122\n" +
	"\x06Status\x18\x06 \x01(\x0e2\x1a.callbackevents.BcTxStatusR\x06Status\x12\x18\n" +
	"\aRealFee\x18\a \x01(\x04R\aRealFee\x12 \n" +
	"\vExplorerURL\x18\b \x01(\tR\vExplorerURL\x1a]\n" +
	"\x0fOperationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.callbackevents.OperationsListR\x05value:\x028\x01\"\xd2\x05\n" +
	"\x05Order\x12G\n" +
	"\x0fOrderIdentifier\x18\x01 \x01(\v2\x1d.callbackevents.OrderIdentityR\x0fOrderIdentifier\x12-\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x19.callbackevents.OrderTypeR\x04Type\x123\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x1b.callbackevents.OrderStatusR\x06Status\x12,\n" +
	"\x11NetworkIdentifier\x18\x04 \x01(\rR\x11NetworkIdentifier\x12.\n" +
	"\x12ProviderIdentifier\x18\x05 \x01(\rR\x12ProviderIdentifier\x12.\n" +
	"\x12MerchantIdentifier\x18\x06 \x01(\tR\x12MerchantIdentifier\x12,\n" +
	"\x11AddressIdentifier\x18\a \x01(\tR\x11AddressIdentifier\x12\x16\n" +
	"\x06Amount\x18\b \x01(\x04R\x06Amount\x12\x18\n" +
	"\aRealFee\x18\t \x01(\x04R\aRealFee\x12k\n" +
	"\x1bEstimationFeeUnitIdentifier\x18\n" +
	" \x01(\v2).callbackevents.EstimationFeeUnitIdentifyR\x1bEstimationFeeUnitIdentifier\x12A\n" +
	"\vOwnerWallet\x18\v \x01(\v2\x1f.callbackevents.OwnerWalletInfoR\vOwnerWallet\x12P\n" +
	"\x12CurrencyIdentifier\x18\f \x01(\v2 .callbackevents.CurrencyIdentityR\x12CurrencyIdentifier\x12,\n" +
	"\x04BcTx\x18\r \x03(\v2\x18.callbackevents.BcTxInfoR\x04BcTx\"\xe9\x02\n" +
	"\n" +
	"OrderEvent\x12$\n" +
	"\rEventIdentity\x18\x01 \x01(\tR\rEventIdentity\x12,\n" +
	"\x11NetworkIdentifier\x18\x02 \x01(\rR\x11NetworkIdentifier\x12.\n" +
	"\x12ProviderIdentifier\x18\x03 \x01(\rR\x12ProviderIdentifier\x12.\n" +
	"\x12MerchantIdentifier\x18\x04 \x01(\tR\x12MerchantIdentifier\x12(\n" +
	"\x0fOrderIdentifier\x18\x05 \x01(\tR\x0fOrderIdentifier\x12\x12\n" +
	"\x04Type\x18\x06 \x01(\tR\x04Type\x12\x1a\n" +
	"\bProducer\x18\a \x01(\tR\bProducer\x12\x18\n" +
	"\aMessage\x18\b \x01(\tR\aMessage\x123\n" +
	"\tOrderInfo\x18\t \x01(\v2\x15.callbackevents.OrderR\tOrderInfo*B\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16PLACEHOLDER_ORDER_TYPE\x10\x00\x12\f\n" +
	"\bWITHDRAW\x10\x01\x12\v\n" +
	"\aDEPOSIT\x10\x02*\x8c\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18PLACEHOLDER_ORDER_STATUS\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\v\n" +
	"\aCREATED\x10\x02\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x03\x12\r\n" +
	"\tCONFIRMED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\x12\v\n" +
	"\aSUCCESS\x10\x06\x12\f\n" +
	"\bCANCELED\x10\a*}\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_PLACEHOLDER\x10\x00\x12\x18\n" +
	"\x14OPERATION_TYPE_SPENT\x10\x01\x12\x1a\n" +
	"\x16OPERATION_TYPE_RECEIVE\x10\x02\x12\x16\n" +
	"\x12OPERATION_TYPE_FEE\x10\x03*\x93\x01\n" +
	"\n" +
	"BcTxStatus\x12\x1c\n" +
	"\x18PLACEHOLDER_BC_TX_STATUS\x10\x00\x12\x13\n" +
	"\x0fBC_TX_IN_MINING\x10\x01\x12\x11\n" +
	"\rBC_TX_SUCCESS\x10\x02\x12\x1a\n" +
	"\x16BC_TX_EXECUTION_FAILED\x10\x03\x12#\n" +
	"\x1fBC_TX_WAITING_FOR_CONFIRMATIONS\x10\x04BQZOgithub.com/crypto-bundle/bc-wallet-common-callback-api/pkg/proto/callbackeventsb\x06proto3"

var (
	file_callback_order_events_proto_rawDescOnce sync.Once
	file_callback_order_events_proto_rawDescData []byte
)

func file_callback_order_events_proto_rawDescGZIP() []byte {
	file_callback_order_events_proto_rawDescOnce.Do(func() {
		file_callback_order_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_callback_order_events_proto_rawDesc), len(file_callback_order_events_proto_rawDesc)))
	})
	return file_callback_order_events_proto_rawDescData
}

var file_callback_order_events_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_callback_order_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_callback_order_events_proto_goTypes = []any{
	(OrderType)(0),                    // 0: callbackevents.OrderType
	(OrderStatus)(0),                  // 1: callbackevents.OrderStatus
	(OperationType)(0),                // 2: callbackevents.OperationType
	(BcTxStatus)(0),                   // 3: callbackevents.BcTxStatus
	(*EstimationFeeIdentify)(nil),     // 4: callbackevents.EstimationFeeIdentify
	(*EstimationFeeUnitIdentify)(nil), // 5: callbackevents.EstimationFeeUnitIdentify
	(*OrderIdentity)(nil),             // 6: callbackevents.OrderIdentity
	(*BcTxIdentity)(nil),              // 7: callbackevents.BcTxIdentity
	(*CurrencyIdentity)(nil),          // 8: callbackevents.CurrencyIdentity
	(*CurrencyInfo)(nil),              // 9: callbackevents.CurrencyInfo
	(*BcTxOperation)(nil),             // 10: callbackevents.BcTxOperation
	(*OperationsList)(nil),            // 11: callbackevents.OperationsList
	(*OwnerWalletInfo)(nil),           // 12: callbackevents.OwnerWalletInfo
	(*BcTxInfo)(nil),                  // 13: callbackevents.BcTxInfo
	(*Order)(nil),                     // 14: callbackevents.Order
	(*OrderEvent)(nil),                // 15: callbackevents.OrderEvent
	nil,                               // 16: callbackevents.BcTxInfo.OperationsEntry
}
var file_callback_order_events_proto_depIdxs = []int32{
	8,  // 0: callbackevents.CurrencyInfo.Identifier:type_name -> callbackevents.CurrencyIdentity
	9,  // 1: callbackevents.BcTxOperation.CurrencyInfo:type_name -> callbackevents.CurrencyInfo
	10, // 2: callbackevents.OperationsList.Operations:type_name -> callbackevents.BcTxOperation
	7,  // 3: callbackevents.BcTxInfo.BcTxIdentifier:type_name -> callbackevents.BcTxIdentity
	16, // 4: callbackevents.BcTxInfo.Operations:type_name -> callbackevents.BcTxInfo.OperationsEntry
	3,  // 5: callbackevents.BcTxInfo.Status:type_name -> callbackevents.BcTxStatus
	6,  // 6: callbackevents.Order.OrderIdentifier:type_name -> callbackevents.OrderIdentity
	0,  // 7: callbackevents.Order.Type:type_name -> callbackevents.OrderType
	1,  // 8: callbackevents.Order.Status:type_name -> callbackevents.OrderStatus
	5,  // 9: callbackevents.Order.EstimationFeeUnitIdentifier:type_name -> callbackevents.EstimationFeeUnitIdentify
	12, // 10: callbackevents.Order.OwnerWallet:type_name -> callbackevents.OwnerWalletInfo
	8,  // 11: callbackevents.Order.CurrencyIdentifier:type_name -> callbackevents.CurrencyIdentity
	13, // 12: callbackevents.Order.BcTx:type_name -> callbackevents.BcTxInfo
	14, // 13: callbackevents.OrderEvent.OrderInfo:type_name -> callbackevents.Order
	11, // 14: callbackevents.BcTxInfo.OperationsEntry.value:type_name -> callbackevents.OperationsList
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_callback_order_events_proto_init() }
func file_callback_order_events_proto_init() {
	if File_callback_order_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callback_order_events_proto_rawDesc), len(file_callback_order_events_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_callback_order_events_proto_goTypes,
		DependencyIndexes: file_callback_order_events_proto_depIdxs,
		EnumInfos:         file_callback_order_events_proto_enumTypes,
		MessageInfos:      file_callback_order_events_proto_msgTypes,
	}.Build()
	File_callback_order_events_proto = out.File
	file_callback_order_events_proto_goTypes = nil
	file_callback_order_events_proto_depIdxs = nil
}
