// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: callback_api.proto

package callbackevents

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewEventRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType EventType              `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=callbackevents.EventType" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*NewEventRequest_OrderEvent
	Event         isNewEventRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewEventRequest) Reset() {
	*x = NewEventRequest{}
	mi := &file_callback_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventRequest) ProtoMessage() {}

func (x *NewEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventRequest.ProtoReflect.Descriptor instead.
func (*NewEventRequest) Descriptor() ([]byte, []int) {
	return file_callback_api_proto_rawDescGZIP(), []int{0}
}

func (x *NewEventRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_PLACEHOLDER_EVENT_TYPE
}

func (x *NewEventRequest) GetEvent() isNewEventRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NewEventRequest) GetOrderEvent() *OrderEvent {
	if x != nil {
		if x, ok := x.Event.(*NewEventRequest_OrderEvent); ok {
			return x.OrderEvent
		}
	}
	return nil
}

type isNewEventRequest_Event interface {
	isNewEventRequest_Event()
}

type NewEventRequest_OrderEvent struct {
	OrderEvent *OrderEvent `protobuf:"bytes,2,opt,name=order_event,json=orderEvent,proto3,oneof"`
}

func (*NewEventRequest_OrderEvent) isNewEventRequest_Event() {}

type NewEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     EventType              `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=callbackevents.EventType" json:"event_type,omitempty"`
	EventIdentity string                 `protobuf:"bytes,2,opt,name=EventIdentity,proto3" json:"EventIdentity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewEventResponse) Reset() {
	*x = NewEventResponse{}
	mi := &file_callback_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEventResponse) ProtoMessage() {}

func (x *NewEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEventResponse.ProtoReflect.Descriptor instead.
func (*NewEventResponse) Descriptor() ([]byte, []int) {
	return file_callback_api_proto_rawDescGZIP(), []int{1}
}

func (x *NewEventResponse) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_PLACEHOLDER_EVENT_TYPE
}

func (x *NewEventResponse) GetEventIdentity() string {
	if x != nil {
		return x.EventIdentity
	}
	return ""
}

var File_callback_api_proto protoreflect.FileDescriptor

const file_callback_api_proto_rawDesc = "" +
	"\n" +
	"\x12callback_api.proto\x12\x0ecallbackevents\x1a\x12order_events.proto\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"\x93\x01\n" +
	"\x0fNewEventRequest\x128\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x19.callbackevents.EventTypeR\teventType\x12=\n" +
	"\vorder_event\x18\x02 \x01(\v2\x1a.callbackevents.OrderEventH\x00R\n" +
	"orderEventB\a\n" +
	"\x05event\"r\n" +
	"\x10NewEventResponse\x128\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x19.callbackevents.EventTypeR\teventType\x12$\n" +
	"\rEventIdentity\x18\x02 \x01(\tR\rEventIdentity2\x84\x01\n" +
	"\vCallbackAPI\x12u\n" +
	"\bNewEvent\x12\x1f.callbackevents.NewEventRequest\x1a .callbackevents.NewEventResponse\"&\x82\xd3\xe4\x93\x02 \"\x1e/api/cryptobundle/v1/new_eventBQZOgithub.com/crypto-bundle/bc-wallet-common-callback-api/pkg/proto/callbackeventsb\x06proto3"

var (
	file_callback_api_proto_rawDescOnce sync.Once
	file_callback_api_proto_rawDescData []byte
)

func file_callback_api_proto_rawDescGZIP() []byte {
	file_callback_api_proto_rawDescOnce.Do(func() {
		file_callback_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_callback_api_proto_rawDesc), len(file_callback_api_proto_rawDesc)))
	})
	return file_callback_api_proto_rawDescData
}

var file_callback_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_callback_api_proto_goTypes = []any{
	(*NewEventRequest)(nil),  // 0: callbackevents.NewEventRequest
	(*NewEventResponse)(nil), // 1: callbackevents.NewEventResponse
	(EventType)(0),           // 2: callbackevents.EventType
	(*OrderEvent)(nil),       // 3: callbackevents.OrderEvent
}
var file_callback_api_proto_depIdxs = []int32{
	2, // 0: callbackevents.NewEventRequest.event_type:type_name -> callbackevents.EventType
	3, // 1: callbackevents.NewEventRequest.order_event:type_name -> callbackevents.OrderEvent
	2, // 2: callbackevents.NewEventResponse.event_type:type_name -> callbackevents.EventType
	0, // 3: callbackevents.CallbackAPI.NewEvent:input_type -> callbackevents.NewEventRequest
	1, // 4: callbackevents.CallbackAPI.NewEvent:output_type -> callbackevents.NewEventResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_callback_api_proto_init() }
func file_callback_api_proto_init() {
	if File_callback_api_proto != nil {
		return
	}
	file_order_events_proto_init()
	file_common_proto_init()
	file_callback_api_proto_msgTypes[0].OneofWrappers = []any{
		(*NewEventRequest_OrderEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callback_api_proto_rawDesc), len(file_callback_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callback_api_proto_goTypes,
		DependencyIndexes: file_callback_api_proto_depIdxs,
		MessageInfos:      file_callback_api_proto_msgTypes,
	}.Build()
	File_callback_api_proto = out.File
	file_callback_api_proto_goTypes = nil
	file_callback_api_proto_depIdxs = nil
}
