// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: callback_common.proto

package callbackevents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_PLACEHOLDER_EVENT_TYPE EventType = 0
	EventType_EVENT_TYPE_ORDER       EventType = 1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "PLACEHOLDER_EVENT_TYPE",
		1: "EVENT_TYPE_ORDER",
	}
	EventType_value = map[string]int32{
		"PLACEHOLDER_EVENT_TYPE": 0,
		"EVENT_TYPE_ORDER":       1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_common_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_callback_common_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_callback_common_proto_rawDescGZIP(), []int{0}
}

var File_callback_common_proto protoreflect.FileDescriptor

const file_callback_common_proto_rawDesc = "" +
	"\n" +
	"\x15callback_common.proto\x12\x0ecallbackevents*=\n" +
	"\tEventType\x12\x1a\n" +
	"\x16PLACEHOLDER_EVENT_TYPE\x10\x00\x12\x14\n" +
	"\x10EVENT_TYPE_ORDER\x10\x01BQZOgithub.com/crypto-bundle/bc-wallet-common-callback-api/pkg/proto/callbackeventsb\x06proto3"

var (
	file_callback_common_proto_rawDescOnce sync.Once
	file_callback_common_proto_rawDescData []byte
)

func file_callback_common_proto_rawDescGZIP() []byte {
	file_callback_common_proto_rawDescOnce.Do(func() {
		file_callback_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_callback_common_proto_rawDesc), len(file_callback_common_proto_rawDesc)))
	})
	return file_callback_common_proto_rawDescData
}

var file_callback_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_callback_common_proto_goTypes = []any{
	(EventType)(0), // 0: callbackevents.EventType
}
var file_callback_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_callback_common_proto_init() }
func file_callback_common_proto_init() {
	if File_callback_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callback_common_proto_rawDesc), len(file_callback_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_callback_common_proto_goTypes,
		DependencyIndexes: file_callback_common_proto_depIdxs,
		EnumInfos:         file_callback_common_proto_enumTypes,
	}.Build()
	File_callback_common_proto = out.File
	file_callback_common_proto_goTypes = nil
	file_callback_common_proto_depIdxs = nil
}
