// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: callback_api.proto

package callbackevents

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallbackAPI_NewEvent_FullMethodName = "/callbackevents.CallbackAPI/NewEvent"
)

// CallbackAPIClient is the client API for CallbackAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Merchant RPC api gateway
type CallbackAPIClient interface {
	NewEvent(ctx context.Context, in *NewEventRequest, opts ...grpc.CallOption) (*NewEventResponse, error)
}

type callbackAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCallbackAPIClient(cc grpc.ClientConnInterface) CallbackAPIClient {
	return &callbackAPIClient{cc}
}

func (c *callbackAPIClient) NewEvent(ctx context.Context, in *NewEventRequest, opts ...grpc.CallOption) (*NewEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewEventResponse)
	err := c.cc.Invoke(ctx, CallbackAPI_NewEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallbackAPIServer is the server API for CallbackAPI service.
// All implementations must embed UnimplementedCallbackAPIServer
// for forward compatibility.
//
// Merchant RPC api gateway
type CallbackAPIServer interface {
	NewEvent(context.Context, *NewEventRequest) (*NewEventResponse, error)
	mustEmbedUnimplementedCallbackAPIServer()
}

// UnimplementedCallbackAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallbackAPIServer struct{}

func (UnimplementedCallbackAPIServer) NewEvent(context.Context, *NewEventRequest) (*NewEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewEvent not implemented")
}
func (UnimplementedCallbackAPIServer) mustEmbedUnimplementedCallbackAPIServer() {}
func (UnimplementedCallbackAPIServer) testEmbeddedByValue()                     {}

// UnsafeCallbackAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallbackAPIServer will
// result in compilation errors.
type UnsafeCallbackAPIServer interface {
	mustEmbedUnimplementedCallbackAPIServer()
}

func RegisterCallbackAPIServer(s grpc.ServiceRegistrar, srv CallbackAPIServer) {
	// If the following call pancis, it indicates UnimplementedCallbackAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallbackAPI_ServiceDesc, srv)
}

func _CallbackAPI_NewEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackAPIServer).NewEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallbackAPI_NewEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackAPIServer).NewEvent(ctx, req.(*NewEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallbackAPI_ServiceDesc is the grpc.ServiceDesc for CallbackAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallbackAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "callbackevents.CallbackAPI",
	HandlerType: (*CallbackAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewEvent",
			Handler:    _CallbackAPI_NewEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "callback_api.proto",
}
